"""
Django settings for cvia_dg_prj project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-wr$o%5j7hj#(mp$uq_ql-n9u&@d8zk4*q4w(771(!s2$8lt@wx"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.18.216', '192.168.1.35', 'localhost','0.0.0.0']
#ALLOWED_HOSTS = ['localhost']


# ✅ Permitir que Angular envíe credenciales
CORS_ALLOW_CREDENTIALS = True

# ✅ Permitir encabezados personalizados
CORS_ALLOW_HEADERS = [
    "content-type",
    "X-CSRFToken",
    "Authorization",
]

# ✅ Configurar cookies de sesión para funcionar con CORS
SESSION_COOKIE_SECURE = False  # Solo en producción con HTTPS ponerlo en True
CSRF_USE_SESSIONS = True

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "cvia_dg_app",
    'corsheaders',  # 🔥 Agregar django-cors-headers
    'rest_framework_simplejwt',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # 🔥 Middleware de CORS
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",  # ✅ Servidor Django
    "http://localhost:4200",   # ✅ Cliente Angular
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",  # ✅ Permitir solicitudes desde Angular
    "http://127.0.0.1:4200",
    "http://192.168.1.35:4200",
    "http://192.168.18.216:4200",
    "http://172.21.78.200:4200",
    "http://localhost:8080",
]

CSRF_COOKIE_SECURE = False  # ✅ Permitir cookies CSRF en localhost
CSRF_COOKIE_HTTPONLY = False  # ✅ Permitir acceso a la cookie desde JavaScript
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax' # También para la cookie de sesión


ROOT_URLCONF = "cvia_dg_prj.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cvia_dg_prj.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#DATABASES = {
#    "default": {
#        "ENGINE": "django.db.backends.sqlite3",
#        "NAME": BASE_DIR / "cvia_dg_app/curriculumia/cvia.db",
#    }
#}

import os

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

AUTH_USER_MODEL = "cvia_dg_app.Usuarios"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            # Aquí definimos que imprima: Nivel, Hora, Archivo, Línea y Mensaje
            'format': '{levelname} {asctime} {filename}:{lineno} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose', # Le decimos que use el formato detallado
        },
    },
    'loggers': {
        # El string vacío '' captura todos los loggers, incluido el tuyo con __name__
        '': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Configuración de SimpleJWT
from datetime import timedelta
SIMPLE_JWT = {
    "ALGORITHM": "HS256",
    # 🔑 Clave de firma compartida con App1
    "SIGNING_KEY": "b7f3c9d8a1e4f0a2c3d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7",  
    
    # Opcional: tiempos de expiración iguales en ambos apps
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=12),

    "USER_ID_FIELD": "username",   # 🔹 usar username en lugar de id
    "USER_ID_CLAIM": "username",   # 🔹 claim dentro del JWT
}