# Generated by Django 5.1 on 2026-05-20 02:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('resume', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre_usuario', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras, números y guion bajo.', regex='^[a-zA-Z0-9_]+$')])),
                ('email1', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Debe ser un email válido.')])),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Debe ser un email válido.')])),
                ('apellido_paterno', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras.', regex='^[a-zA-Z]+$')])),
                ('apellido_materno', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras.', regex='^[a-zA-Z]+$')])),
                ('nombres', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras.', regex='^[a-zA-Z ]+$')])),
                ('celular', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Debe ser un número de celular válido.', regex='^\\d{9,15}$')])),
                ('direccion', models.CharField(max_length=255)),
                ('tipo_documento_identidad', models.CharField(choices=[('01', 'Documento Nacional de Identidad (DNI)'), ('02', 'Pasaporte'), ('03', 'Carnet de Extranjería'), ('04', 'Registro Único de Contribuyentes (RUC)')], max_length=2, validators=[django.core.validators.RegexValidator(message='Debe ser un tipo de documento válido.', regex='^(01|02|03|04)$')])),
                ('numero_documento_identidad', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('situacion', models.CharField(choices=[('1', 'Normal'), ('2', 'Bloqueado'), ('3', 'Suspendido'), ('4', 'Baja')], default='1', max_length=1)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DatosPrimerCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('nombres', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('profesion', models.CharField(max_length=200)),
                ('objetivo', models.TextField()),
                ('experiencia', models.TextField(blank=True, null=True)),
                ('cursos', models.TextField(blank=True, null=True)),
                ('habilidades', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ip_creacion', models.CharField(max_length=50)),
                ('ip_actualizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='cvs_pdf/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_datos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos de Primer CV',
                'verbose_name_plural': 'Datos de Primeros CVs',
            },
        ),
        migrations.CreateModel(
            name='FortalezasHabilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividades', models.TextField(help_text='Actividades o experiencias desarrolladas en los últimos años.')),
                ('adjuntar_al_cv', models.BooleanField(default=False, verbose_name='Considerar en el CV')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ip_creacion', models.CharField(max_length=50)),
                ('ip_actualizacion', models.CharField(max_length=50, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_potencial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis de Potencial',
                'verbose_name_plural': 'Análisis de Potenciales',
            },
        ),
        migrations.CreateModel(
            name='UsuariosPasswords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=128)),
                ('salt', models.CharField(max_length=64)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=1)),
                ('condicion', models.CharField(choices=[('1', 'Normal'), ('2', 'Bloqueado Temporalmente')], default='1', max_length=1)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('tiempo_bloqueo', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
